[build]
  # Directory where your build output files are located (usually 'public' for Gatsby)
  publish = "public"  # Gatsby outputs build files to the 'public' directory

  # Command to run to build your site (e.g., for Gatsby)
  command = "yarn run build"  # or 'npm run build' if you're using npm instead of Yarn

  # Directory to run the build from (use the root of the project or specify subdirectory for monorepos)
  base = "/"  # Use '/' for the root project or specify the subfolder name if using a monorepo

[[redirects]]
  # Redirect rule example: Redirect HTTP to HTTPS
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[plugins]]
  # Use the Gatsby plugin for deploying Gatsby sites to Netlify
  package = "@netlify/plugin-gatsby"  # This is the correct plugin for Gatsby

[functions]
  # Directory where your serverless functions are located (usually 'netlify/functions')
  directory = "netlify/functions"
  
# Optional: Specify environment variables
[env]
  NODE_ENV = "production"
  CUSTOM_ENV_VAR = "value"
